stages:    
  - prepare
  - compile

variables:
  MW_MINGW64_LOC: "C:\Tools\MinGW64\4.9.2-airbus"

.windows-task:
  tags:
    - Windows
  before_script:
    - $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
    - $env:ED247_TOOLS = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("ED247_TOOLS","Machine"))
  script:
    - launch_matlab $RELEASE -batch "$CMD"

windows:prepare:
  stage: prepare  
  needs: []
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Dependencies.runOnGitLabCI()

windows:compile:
  stage: compile  
  needs: ["windows:prepare"]
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Compile.runOnGitLabCI()