stages:    
  - prepare

windows:prepare:
  tags:
    - Windows
  stage: prepare  
  needs: []
  before_script:
    - $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
    - $env:ED247_TOOLS = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("ED247_TOOLS","Machine"))
  script:
    - echo $env:path
    - echo $env:ED247_TOOLS
    - launch_matlab R2020b -batch "ci.Dependencies.runOnGitLabCI()"
