stages:    
  - prepare

windows:prepare:
  tags:
    - Windows
  stage: prepare  
  needs: []
  script:
    - echo $env:path
    - echo $env:ED247_TOOLS
    - launch_matlab R2020b -batch "ci.Dependencies.runOnGitLabCI()"
