stages:    
  - prepare
  - compile
  - test

variables:
  MW_MINGW64_LOC: "C:\\Tools\\MinGW64\\4.9.2-airbus"
  LIBXML_LOC: "C:\\Temp\\ED247\\Dependencies\\libxml2"
  ED247_LOC: "C:\\Temp\\ED247\\Dependencies\\ed247"
  QNX_LOC: "C:\\Temp\\ED247\\Dependencies\\ed247_qnx"

.windows-task:
  tags:
    - Windows
  before_script:
    - $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
    - $env:ED247_TOOLS = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("ED247_TOOLS","Machine"))
  script:
    - launch_matlab $RELEASE -batch "$CMD"

windows:prepare:
  stage: prepare  
  needs: []
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Dependencies.runOnGitLabCI()

windows:mex:
  stage: compile  
  needs: ["windows:prepare"]
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Compile.runOnGitLabCI()
  artifacts:
    name: Windows-MEX
    paths:
        - libraries/ed247/*.mex*

windows:test:
  stage: test  
  needs: ["windows:mex"]
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Test.runOnGitLabCI()
  artifacts:
    reports:
      cobertura: ./Coverage.xml
      junit: ./TestResults.xml