stages:    
  - prepare
  - compile
  - test
  - package

.windows-task:
  variables:
    MW_MINGW64_LOC: "C:\\Tools\\MinGW64\\4.9.2-airbus"
    LIBXML_LOC: "C:\\Temp\\ED247\\Dependencies\\libxml2"
    ED247_LOC: "C:\\Temp\\ED247\\Dependencies\\ed247"
    QNX_LOC: "C:\\Temp\\ED247\\Dependencies\\ed247_qnx"
  tags:
    - Windows
  before_script:
    - $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
    - $env:ED247_TOOLS = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("ED247_TOOLS","Machine"))
  script:
    - launch_matlab $RELEASE -batch "$CMD"

.linux-task:
  tags:
    - Linux
    - Docker

windows:prepare:
  stage: prepare  
  needs: []
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Dependencies.runOnGitLabCI()
    
linux:prepare:
  extends: .linux-task
  stage: prepare
  needs: []
  image: docker:19.03.12
  script:
    - docker build --no-cache . -t matlab-ed247:r2020b --build-arg ARTIFACT_PROJECT_TOKEN=$ARTIFACT_PROJECT_TOKEN --build-arg ARTIFACT_PROJECT_ID=$ARTIFACT_PROJECT_ID --build-arg ARTIFACT_PROJECT_BRANCH=$ARTIFACT_PROJECT_BRANCH --build-arg ED247_LOC=/tools/ed247 --build-arg LIBXML_LOC=/tools/libxml2

windows:mex:
  stage: compile  
  needs: ["windows:prepare"]
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Compile.runOnGitLabCI()
  artifacts:
    name: Windows-MEX
    paths:
        - libraries/ed247/*.mex*

linux:mex:
  stage: compile
  needs: ["linux:prepare"]
  extends: .linux-task
  image: matlab-ed247:r2020b
  script: matlab -r "ci.Compile.runOnGitLabCI()"
  artifacts:
    name: Linux-MEX
    paths:
        - libraries/ed247/*.mex*

windows:test:
  stage: test  
  needs: ["windows:mex"]
  extends: .windows-task
  variables:
    RELEASE: R2020b
    CMD: ci.Test.runOnGitLabCI()
  artifacts:
    reports:
      cobertura: ./Coverage.xml
      junit: ./TestResults.xml

linux:test:
  stage: test  
  needs: ["linux:mex"]
  extends: .linux-task
  image: matlab-ed247:r2020b
  script: matlab -r "ci.Compile.runOnGitLabCI()"
  artifacts:
    reports:
      cobertura: ./Coverage.xml
      junit: ./TestResults.xml
 
