stages:    
  - prepare
  - compile

.windows-task:
  tags:
    - Windows
  before_script:
    - $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
    - $env:ED247_TOOLS = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("ED247_TOOLS","Machine"))

windows:prepare:
  stage: prepare  
  needs: []
  extends: .windows-task
  script:
    - launch_matlab R2020b -batch "ci.Dependencies.runOnGitLabCI()"

windows:compile:
  stage: compile  
  needs: []
  extends: .windows-task
  script:
    - launch_matlab R2020b -batch "ci.Compile.runOnGitLabCI()"