stages:    
  - prepare
  - compile
  - test
  - package

windows:prepare:
  tags:
    - Windows
  stage: prepare  
  needs: []
  scripts:
    - launch_matlab R2020b -batch "ci.Dependencies.runOnGitLabCI()"
