/* Copyright 2021 The MathWorks, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED AND USED BY POLYSPACE.
 * DO NOT MODIFY IT.
 */

#ifdef __cplusplus
extern "C" {
#endif


int_T __ed247_sfun__instanceId;
/*** S-Function instance 1 ('<Root>/ED247_Configuration/ed247_sfun') ***/

const uint8_T __ed247_sfun_i1_DialogPrm1 = 0;
mwSize __ed247_sfun_i1_DialogPrm1___dims[2] = { 1, 1 };
const int8_T __ed247_sfun_i1_DialogPrm2[116] = { 67, 58, 92, 70, 105, 108, 101, 115, 92, 83, 65, 78, 68, 66, 79, 88, 92, 103, 105, 116, 92, 69, 68, 50, 52, 55, 92, 101, 100, 50, 52, 55, 95, 102, 111, 114, 95, 115, 105, 109, 117, 108, 105, 110, 107, 92, 100, 111, 99, 92, 101, 120, 97, 109, 112, 108, 101, 115, 92, 114, 101, 99, 101, 105, 118, 101, 65, 52, 50, 57, 92, 101, 99, 105, 99, 95, 102, 117, 110, 99, 95, 101, 120, 99, 104, 97, 110, 103, 101, 95, 97, 52, 50, 57, 95, 117, 99, 95, 116, 101, 115, 116, 101, 114, 95, 115, 105, 109, 112, 108, 101, 46, 120, 109, 108, 0 };
mwSize __ed247_sfun_i1_DialogPrm2___dims[2] = { 1, 116 };
const int8_T __ed247_sfun_i1_DialogPrm3[67] = { 67, 58, 92, 70, 105, 108, 101, 115, 92, 83, 65, 78, 68, 66, 79, 88, 92, 103, 105, 116, 92, 69, 68, 50, 52, 55, 92, 101, 100, 50, 52, 55, 95, 102, 111, 114, 95, 115, 105, 109, 117, 108, 105, 110, 107, 92, 116, 101, 115, 116, 115, 92, 95, 102, 105, 108, 101, 115, 92, 116, 109, 112, 46, 108, 111, 103, 0 };
mwSize __ed247_sfun_i1_DialogPrm3___dims[2] = { 1, 67 };
const uint8_T __ed247_sfun_i1_DialogPrm4 = 0;
mwSize __ed247_sfun_i1_DialogPrm4___dims[2] = { 1, 1 };
const real64_T __ed247_sfun_i1_DialogPrm5 = -1.000000;
mwSize __ed247_sfun_i1_DialogPrm5___dims[2] = { 1, 1 };
extern SimStruct * const __ed247_sfun_i1_S;
volatile int_T __ed247_sfun_i1_tid;


void __ed247_sfun_i1_Start(void) {
    __ed247_sfun__instanceId = 1;
    mdlStart( __ed247_sfun_i1_S);
}



void __ed247_sfun_i1_Output(void) {
    __ed247_sfun__instanceId = 1;
    mdlOutputs( __ed247_sfun_i1_S, __ed247_sfun_i1_tid);
}



void __ed247_sfun_i1_Terminate(void) {
    __ed247_sfun__instanceId = 1;
    mdlTerminate( __ed247_sfun_i1_S);
}



void __ed247_sfun_i1_Update(void) {
    __ed247_sfun__instanceId = 1;
    mdlUpdate( __ed247_sfun_i1_S, __ed247_sfun_i1_tid);
}


void __ed247_sfun_i1_init_globals(void) {
}



/*** S-Function instance 2 ('<Root>/ED247_Receive') ***/

const uint8_T __ed247_sfun_i2_DialogPrm1 = 1;
mwSize __ed247_sfun_i2_DialogPrm1___dims[2] = { 1, 1 };
const uint8_T __ed247_sfun_i2_DialogPrm2 = 0;
mwSize __ed247_sfun_i2_DialogPrm2___dims[2] = { 1, 1 };
const uint8_T __ed247_sfun_i2_DialogPrm3 = 0;
mwSize __ed247_sfun_i2_DialogPrm3___dims[2] = { 1, 1 };
const uint8_T __ed247_sfun_i2_DialogPrm4 = 1;
mwSize __ed247_sfun_i2_DialogPrm4___dims[2] = { 1, 1 };
const real64_T __ed247_sfun_i2_DialogPrm5 = -1.000000;
mwSize __ed247_sfun_i2_DialogPrm5___dims[2] = { 1, 1 };
uint32_T __ed247_sfun_i2_DWork1;
uint32_T __ed247_sfun_i2_DWork2;
uint32_T __ed247_sfun_i2_DWork3;
uint8_T __ed247_sfun_i2_Out1[4];
int_T __ed247_sfun_i2_Out1___dims[1] = { 4 };
uint8_T __ed247_sfun_i2_Out2;
int_T __ed247_sfun_i2_Out2___dims[1] = { 1 };
uint8_T __ed247_sfun_i2_Out3[4];
int_T __ed247_sfun_i2_Out3___dims[1] = { 4 };
uint8_T __ed247_sfun_i2_Out4;
int_T __ed247_sfun_i2_Out4___dims[1] = { 1 };
uint8_T __ed247_sfun_i2_Out5[4];
int_T __ed247_sfun_i2_Out5___dims[1] = { 4 };
uint8_T __ed247_sfun_i2_Out6;
int_T __ed247_sfun_i2_Out6___dims[1] = { 1 };
extern SimStruct * const __ed247_sfun_i2_S;
volatile int_T __ed247_sfun_i2_tid;


void __ed247_sfun_i2_Start(void) {
    __ed247_sfun__instanceId = 2;
    mdlStart( __ed247_sfun_i2_S);
}



void __ed247_sfun_i2_Output(void) {
    __ed247_sfun__instanceId = 2;
    mdlOutputs( __ed247_sfun_i2_S, __ed247_sfun_i2_tid);
}



void __ed247_sfun_i2_Terminate(void) {
    __ed247_sfun__instanceId = 2;
    mdlTerminate( __ed247_sfun_i2_S);
}



void __ed247_sfun_i2_Update(void) {
    __ed247_sfun__instanceId = 2;
    mdlUpdate( __ed247_sfun_i2_S, __ed247_sfun_i2_tid);
}


void __ed247_sfun_i2_init_globals(void) {
}





/*** SimStruct overridden functions ***/

int_T ssGetNumInputPorts(SimStruct *S) {
    return 0;
}

